### ISSUE TITLE
Authenticate via .authinfo.gpg

### ISSUE THREAD

**Issue by fleimgruber** [alphapapa/matrix-client.el#88]
It would be convenient to authenticate using the credentials inside an .authinfo.gpg file as is done in `erc` [here](https://github.com/emacs-mirror/emacs/blob/d0e2a341dd9a9a365fd311748df024ecb25b70ec/lisp/erc/erc.el#L2047). This would be (less) useful for users which cache their token and (more) useful for users which do not. Something along the lines of (essentially stolen from erc):

``` emacs-lisp
(defun matrix-client-authinfo-password (server user)
  (let ((secret
         (plist-get
          (nth 0
               (auth-source-search :host server
                                   :max 1
                                   :user user
                                   :require '(:secret)))
          :secret)))
    (if (functionp secret)
        (funcall secret)
      secret)))
```

To be used in `matrix-client-connect` if it does not return nil.
If you think it is useful I would prepare a PR.

**Comment by alphapapa** [comment]
Hi,

Unfortunately, there are significant issues with `authinfo` that make it very difficult to use effectively.  See discussions linked at https://github.com/alphapapa/matrix-client.el/issues/81.

If you really need this feature, I'd be willing to consider a PR that made it optional, using the current code by default.  But I can't promise that I would accept such a PR, because I'm skeptical that it's worth the effort.

**Comment by fleimgruber** [comment]
I see. Fair enough. I will then either go with token caching or advice. Thanks for the prompt answer and maintenance!
