### ISSUE TITLE
Void variable `notify` when byte compiling

### ISSUE THREAD

**Issue by paulapatience** [alphapapa/matrix-client.el#97]
Interactively calling either of the (autoloaded) `matrix-client-connect` and `matrix-client-frame` functions fails with the error:

```
require: Symbol’s value as variable is void: notify
```

after installing the package in [Doom Emacs](https://github.com/hlissner/doom-emacs):

```bash
$ doom version 2>/dev/null
Doom v2.0.9 (Emacs v26.3)
Branch: develop
Commit: 4b20c7206ef92ac4639c412beca813ebc15e4e88
Build date: 2020-03-13 17:34:44 -0400
```

with [`straight.el`](https://github.com/raxod502/straight.el) by adding the following to `$DOOMDIR/packages.el`:

```elisp
(package! matrix-client
  :recipe (:host github :repo "alphapapa/matrix-client.el"))
```

and running `doom sync` (which byte-compiles the package and its dependencies).

The version of the `matrix-client.el` package that `straight.el` installed is, at the time of writing, `master`'s HEAD:

```bash
$ (cd $HOME/.emacs.d/.local/straight/repos/matrix-client.el && git rev-parse HEAD)
59c792423fd0503f1375f356bec56130e65d3b51
```

Requiring `'matrix-client` before calling `matrix-client-connect` or `matrix-client-frame` does not fix the problem. However, removing all byte-compiled files does:

```bash
(cd $HOME/.emacs.d/.local/straight/build/matrix-client && rm -f *.elc)
```

The problem is that `matrix-notifications.el` does not require `'matrix-client-room` during compilation, so the macro `matrix-client-def-room-command` is undefined. The solution is to require `'matrix-client-room` during compilation:

```diff
diff --git a/matrix-notifications.el b/matrix-notifications.el
index 2b44995..140c1b1 100644
--- a/matrix-notifications.el
+++ b/matrix-notifications.el
@@ -34,6 +34,8 @@
 
 (require 'anaphora)
 
+(eval-when-compile (require 'matrix-client-room))
+
 ;;;; Customization
 
 (defgroup matrix-client-notifications nil
```

While this fixes the problem, `matrix-notifications.el` uses functions from `matrix-client-room.el` (`matrix-client-update-last-seen`, `matrix-client--find-propertized-string`, and maybe more), so perhaps it would be better to require it at runtime as well, by forgoing `eval-when-compile`.

I would submit a pull request, but I noticed that this file also uses `matrix-room` and `matrix-user-displayname` from `matrix-api-r0.3.0.el`, and `matrix-client-sessions` and `matrix-client-event-timestamp` from `matrix-client.el`, and maybe more, and as I am unaware of how Emacs handles circular dependencies, I don't know if `matrix-notifications.el` should require `'matrix-api-r0.3.0` and `'matrix-client`.

**Comment by alphapapa** [comment]
Hi Paul,

Thanks for the report and for your patience (forgive me, but when I realized that's also your name, I chuckled a bit when trying to figure out how to explain that I'm not joking about your name :)).

Emacs doesn't handle circular dependencies at all; it's up to the author to handle that.

Issues like this are one reason the package hasn't been published to MELPA yet.  It needs some tidying up.  But there are other reasons as well, so that tidying up hasn't been important enough to do yet.

I don't have this problem when installing with Quelpa, but I don't use Doom or Straight, so maybe there's something going on there.

Anyway, please try the branch in the commit above and let me know if it fixes the problem for you.  You should be able to specify it in the `package!` form, I guess.  If it fixes it, I'll merge it to `master`.

**Comment by paulapatience** [comment]
My last name does tend to elicit comments, so don't worry about it :).

I've tested your fix and it works. Thanks.

**Comment by rushsteve1** [comment]
I had the exact same issue, and the `fix/97` branch also fixed it for me.

**Comment by seanfarley** [comment]
Ah, I was having this error as well! This fixes the error for me, too (but warns about, most likely, circular problems in bufler).

**Comment by alphapapa** [comment]
Closing issues and archiving repository.  Please see https://github.com/alphapapa/ement.el for the new client.
